### ISSUE TITLE
Anything an AW noob could help out with?

### ISSUE THREAD

**Issue by Powersource** [johan-bjareholt/aw-server-rust#1]
@johan-bjareholt 

i.e. any `good first issue`s?

**Comment by johan-bjareholt** [comment]
The datastore is stable since last week now, so things are starting to work pretty well now.

But the first things that come to mind would be:
- Import REST endpoint (really important, so we can get data from exporting from aw-server python)
- Export REST endpoint
- rewrite some transform functions from python to rust (needed for full query support later, flood and merge/chunk are important)
- If you search for TODO or FIXME in the src directory there might also be a few misc notes, some are large and some are minor

The only thing you should not take a look at is the query code, it is both dirty and complicated currently.
The rest obviously isn't polished either, so just misc refactoring is appreciated aswell.

**Comment by johan-bjareholt** [comment]
Added these notes to the README, closing
